[versions]
androidGradlePlugin = "8.1.0-beta03"
androidPlugin = "8.1.0-beta04"
androidMaterial = "1.9.0"
androidxActivity = "1.7.2"
androidxAppCompat = "1.6.1"
androidxCore = "1.10.1"
androidxComposeFoundation = "1.4.3"
androidxComposeMaterial = "1.4.3"
androidxComposeUi = "1.4.3"
androidxTestCore = "1.5.0"
androidxTestEspresso = "3.5.1"
androidxTestExt = "1.1.5"
guava = "31.0.1-android"
gson = "2.10.1"
jdk8LibsDesugar = "2.0.3"
junit4 = "4.13.2"
junitPlugin = "1.1.5"
kotlin = "1.8.0"
kotlinxCoroutines = "1.6.4"
ksp = "1.8.0-1.0.9"
mockito = "5.2.0"
mockitoKotlin = "1.6.0"
tagd = "0.0.0-alpha06-snapshot"

[libraries]
android-material = { group = "com.google.android.material", name = "material", version.ref = "androidMaterial" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidxActivity" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "androidxComposeFoundation" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "androidxComposeMaterial" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidxComposeUi" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidxComposeUi" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "androidxComposeUi" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxTestEspresso" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExt" }
androidx-test-junit-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
jdk8plus-libs-desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "jdk8LibsDesugar" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-inline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockito" }
mockito-kotlin = { group = "com.nhaarman", name = "mockito-kotlin", version.ref = "mockitoKotlin" }
tagd-arch = { group = "io.github.pavan2you", name = "kmm-tagd-arch", version.ref = "tagd" }
tagd-android = { group = "io.github.pavan2you", name = "kmm-tagd-android", version.ref = "tagd" }

# Dependencies of the included build-logic
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidPlugin" }
android-library = { id = "com.android.library", version.ref = "androidPlugin" }
android-test = { id = "com.android.test", version.ref = "androidPlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }